version: '3'
services:
  webscrapper-api:
    image: webscrapper
    container_name: scrapper-api
    restart: unless-stopped
    build: .
    ports: 
      - '8605:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
